[tool.poetry]
name = "chess-board"
version = "0.1.0"
description = ""
authors = ["Klace Koch <koch.klace@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
